<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <AssemblyName>SickoMenu</AssemblyName>
    <Description>A powerful utility for Among Us designed to enrich your game experience</Description>
    <Version>5.0.0</Version>
    <FileVersion>5.0.0.0</FileVersion>
    <RootNamespace>SickoMenu</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json;https://nuget.bepinex.dev/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(AmongUsDir)' == ''">
    <AmongUsDir>$(MSBuildProjectDirectory)\AmongUsStub</AmongUsDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="Il2CppInterop.Common" Version="1.5.1" />
    <PackageReference Include="Il2CppInterop.Runtime" Version="1.5.1" />
    <PackageReference Include="HarmonyX" Version="2.10.1" />
  </ItemGroup>

  <Target Name="CopyToMods" AfterTargets="Build" Condition="Exists('$(AmongUsDir)/BepInEx')">
    <Copy SourceFiles="$(OutputPath)/$(AssemblyName).dll" DestinationFolder="$(AmongUsDir)/BepInEx/plugins/$(AssemblyName)" />
  </Target>
</Project>
