<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SickoMenu</AssemblyName>
    <Description>A powerful utility for Among Us designed to enrich your game experience</Description>
    <RootNamespace>SickoMenu</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <Target Name="CopyToMods" AfterTargets="Build" Condition="Exists('$(AmongUsDir)/BepInEx')">
    <Copy SourceFiles="$(OutputPath)/$(AssemblyName).dll" DestinationFolder="$(AmongUsDir)/BepInEx/plugins/$(AssemblyName)" />
  </Target>
</Project>
